apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: dep-reader
rules:
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployment"]
  verbs: ["get", "watch", "list"]
