apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
